---
title: "Validation"
author: "Mary Ann Binuya"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
  pdf_document: default
---


# Aims
1. To externally validate BOADICEA.

# Set-up
```{r setup, include=FALSE}
  library(readxl)
  library(ggplot2)
  library(dplyr)
  library(survival)
  library(survminer)
  library(rms)
  library(boot)
  library(knitr)
  library(kableExtra)
  library(viridis)
```

# Load required datasets
```{r load}
load("WS_04_Descriptive.RData")

  dat <- dat_nodcis # change data as needed
  nrow(dat)
  table(dat$omgedrag, useNA="always")

# List of predicted risks based on different models
  predrisk_cols <- list(dat$predrisk_mod1, dat$predrisk_mod2,
                        dat$predrisk_mod3a, dat$predrisk_mod3b,
                        dat$predrisk_mod4,
                        dat$predrisk_mod5a, dat$predrisk_mod5b)
  model_names <- c("Model1", "Model2", "Model3a", "Model3b", "Model4", "Model5a",  "Model5b")
  
# Load functions to calculate performance
  source("Functions/perf_functions.R")
  
# Time horizon
  tmax <- 5
  
# Weights
  dat$wt <- dat$wt_KM

  tapply(dat$wt, dat$bc, summary)
```

# External validation {.tabset}
## Discrimination
```{r AUC}
# Define the function to compute C-index and confidence intervals
  computeCindex_with_ci <- function(predrisk_col) {
    cind_est <- round(computeCindex(outcome_FUP = dat$futime,
                                    outcome_num = dat$bc,
                                    predictions = predrisk_col,
                                    tp = tmax,
                                    weights = dat$wt), 2)
    x1 <- 1:nrow(dat)
    b1 <- boot(x1, function(u, i)
      computeCindex(
        outcome_FUP = dat$futime[i],
        outcome_num = dat$bc[i],
        predictions = predrisk_col[i],
        tp = tmax,
        weights = dat$wt[i]),
      R = 1000)
    b1_ci <- boot.ci(b1, type = c("norm", "basic", "perc"))
    result <- paste0(cind_est, " (", round(b1_ci$percent[4], 2), ", ", round(b1_ci$percent[5], 2), ")")
    return(result)
  }

# Initialize a dataframe to store results
  res_Cindex <- data.frame(
    Model = character(),
    Cindex = character(),
    stringsAsFactors = FALSE
  )

# Apply function to list of predicted risks
  for (i in seq_along(predrisk_cols)) {
    cindex_result <- computeCindex_with_ci(predrisk_cols[[i]])
    res_Cindex <- rbind(res_Cindex, data.frame(Model = model_names[i], Cindex = cindex_result, stringsAsFactors = FALSE))
  }

# Results
  rownames(res_Cindex) <- NULL

  kable(res_Cindex,
        format = "html", 
      col.names = c("Model", "C-index")
      ) %>%
    kable_styling(
      full_width = FALSE, 
      bootstrap_options = c("striped", "hover")
      )
```

## Calibration {.tabset}
### O/E ratio
```{r OEratio}
# Define the function to compute O/E ratio and confidence intervals
  computeOEratio_with_ci <- function(predrisk_col) {
    oe_ratio_est <- round(computeOEratio(outcome_FUP = dat$futime,
                                         outcome_num = dat$bc,
                                         predictions = predrisk_col,
                                         tp = tmax,
                                         weights = dat$wt), 2)
    x1 <- 1:nrow(dat)
    b2 <- boot(x1, function(u, i)
      computeOEratio(
        outcome_FUP = dat$futime[i],
        outcome_num = dat$bc[i],
        predictions = predrisk_col[i],
        tp = tmax,
        weights = dat$wt[i]),
      R = 1000)
    b2_ci <- boot.ci(b2, type = c("norm", "basic", "perc"))
    result <- paste0(oe_ratio_est, " (", round(b2_ci$percent[4], 2), ", ", round(b2_ci$percent[5], 2), ")")
    return(result)
  }

# Initialize a dataframe to store results
  res_OEratio <- data.frame(
    Model = character(),
    OE_Ratio = character(),
    stringsAsFactors = FALSE
  )

# Apply function to list of predicted risks
  for (i in seq_along(predrisk_cols)) {
    oe_ratio_result <- computeOEratio_with_ci(predrisk_cols[[i]])
    res_OEratio <- rbind(res_OEratio, data.frame(Model = model_names[i], OE_Ratio = oe_ratio_result, stringsAsFactors = FALSE))
  }

# Results
  rownames(res_OEratio) <- NULL

  kable(res_OEratio,
        format = "html", 
      col.names = c("Model", "O/E Ratio")
      ) %>%
    kable_styling(
      full_width = FALSE, 
      bootstrap_options = c("striped", "hover")
      )
```

### Slope (absolute risk scale)
```{r calslope_main}
# Define the function to compute calibration slope and confidence intervals
  computeSlope_with_ci <- function(predrisk_col) {
    cslope_est <- round(computeSlope(outcome_FUP = dat$futime,
                                         outcome_num = dat$bc,
                                         predictions = predrisk_col,
                                         tp = tmax,
                                         weights = dat$wt), 2)
    x1 <- 1:nrow(dat)
    b3 <- boot(x1, function(u, i)
      computeSlope(outcome_FUP = dat$futime[i],
                       outcome_num = dat$bc[i],
                       predictions = predrisk_col[i],
                       tp = tmax,
                       weights = dat$wt[i]),
      R = 1000)
    b3_ci <- boot.ci(b3, type = c("norm", "basic", "perc"))
    result <- paste0(cslope_est, " (", round(b3_ci$percent[4], 2), ", ", round(b3_ci$percent[5], 2), ")")
    return(result)
  }

# Initialize a dataframe to store results
  res_Slope <- data.frame(
    Model = character(),
    Slope = character(),
    stringsAsFactors = FALSE
  )

# Apply function to list of predicted risks
  for (i in seq_along(predrisk_cols)) {
    calibration_slope_result <- computeSlope_with_ci(predrisk_cols[[i]])
    res_Slope <- rbind(res_Slope, data.frame(Model = model_names[i], Slope = calibration_slope_result, stringsAsFactors = FALSE))
  }

# Results
  rownames(res_Slope) <- NULL

  kable(res_Slope,
        format = "html", 
      col.names = c("Model", "Calibration Slope")
      ) %>%
    kable_styling(
      full_width = FALSE, 
      bootstrap_options = c("striped", "hover")
      )
```

### Slope (log cumhaz scale)
```{r calslope_loglog}
# Define the function to compute calibration slope and confidence intervals
  computeSlope_loglog_with_ci <- function(predrisk_col) {
    cslope_est <- round(computeSlope_loglog(outcome_FUP = dat$futime,
                                         outcome_num = dat$bc,
                                         predictions = predrisk_col,
                                         tp = tmax,
                                         weights = dat$wt), 2)
    x1 <- 1:nrow(dat)
    b3 <- boot(x1, function(u, i)
      computeSlope_loglog(outcome_FUP = dat$futime[i],
                       outcome_num = dat$bc[i],
                       predictions = predrisk_col[i],
                       tp = tmax,
                       weights = dat$wt[i]),
      R = 1000)
    b3_ci <- boot.ci(b3, type = c("norm", "basic", "perc"))
    result <- paste0(cslope_est, " (", round(b3_ci$percent[4], 2), ", ", round(b3_ci$percent[5], 2), ")")
    return(result)
  }

# Initialize a dataframe to store results
  res_Slope_loglog <- data.frame(
    Model = character(),
    Slope_loglog = character(),
    stringsAsFactors = FALSE
  )

# Apply function to list of predicted risks
  for (i in seq_along(predrisk_cols)) {
    calibration_slope_loglog_result <- computeSlope_loglog_with_ci(predrisk_cols[[i]])
    res_Slope_loglog <- rbind(res_Slope_loglog, data.frame(Model = model_names[i], Slope_loglog = calibration_slope_loglog_result, stringsAsFactors = FALSE))
  }

# Results
  rownames(res_Slope_loglog) <- NULL

  kable(res_Slope_loglog,
        format = "html", 
      col.names = c("Model", "Calibration Slope: Log Cumulative Hazard Scale")
      ) %>%
    kable_styling(
      full_width = FALSE, 
      bootstrap_options = c("striped", "hover")
      )
```

## Calibration plots
```{r calplots_quantiles, fig.width=5.5, fig.height=11}
# Set plot area
par(mfrow = c(ceiling(length(predrisk_cols) / 2), 2), mar = c(4, 4, 2, 1))

# Apply plotting function to list of predicted risks
for (i in seq_along(predrisk_cols)) {
  calplot_quintiles(predrisk_cols[[i]], model_names[i])
}

par(mfrow = c(1, 1))

# Set plot area
par(mfrow = c(ceiling(length(predrisk_cols) / 2), 2), mar = c(4, 4, 2, 1))

# Apply plotting function to list of predicted risks
for (i in seq_along(predrisk_cols)) {
  calplot_deciles(predrisk_cols[[i]], model_names[i], limit = 0.06)
}

par(mfrow = c(1, 1))
```

## Calibration plots (smooth)
```{r calplots_smooth, fig.width=5.5, fig.height=11}
par(mfrow = c(ceiling(length(predrisk_cols) / 2), 2), mar = c(4, 4, 2, 1))

calplot_smooth(dat, "predrisk_mod1", tmax = tmax, main = "Model 1",
               C = res_Cindex$Cindex[res_Cindex$Model == "Model1"],
               calslope = res_Slope$Slope[res_Slope$Model == "Model1"],
               OEratio = res_OEratio$OE_Ratio[res_OEratio$Model == "Model1"],
               limit = 0.05, markers = FALSE, g = 5)
calplot_smooth(dat, "predrisk_mod2", tmax = tmax, main = "Model 2",
               C = res_Cindex$Cindex[res_Cindex$Model == "Model2"],
               calslope = res_Slope$Slope[res_Slope$Model == "Model2"],
               OEratio = res_OEratio$OE_Ratio[res_OEratio$Model == "Model2"],
               limit = 0.08, markers = FALSE, g = 5)
calplot_smooth(dat, "predrisk_mod3a", tmax = tmax, main = "Model 3a",
               C = res_Cindex$Cindex[res_Cindex$Model == "Model3a"],
               calslope = res_Slope$Slope[res_Slope$Model == "Model3a"],
               OEratio = res_OEratio$OE_Ratio[res_OEratio$Model == "Model3a"],
               limit = 0.08, markers = FALSE, g = 5)
calplot_smooth(dat, "predrisk_mod3b", tmax = tmax, main = "Model 3b",
               C = res_Cindex$Cindex[res_Cindex$Model == "Model3b"],
               calslope = res_Slope$Slope[res_Slope$Model == "Model3b"],
               OEratio = res_OEratio$OE_Ratio[res_OEratio$Model == "Model3b"],
               limit = 0.08, markers = FALSE, g = 5)
calplot_smooth(dat, "predrisk_mod4", tmax = tmax, main = "Model 4",
               C = res_Cindex$Cindex[res_Cindex$Model == "Model4"],
               calslope = res_Slope$Slope[res_Slope$Model == "Model4"],
               OEratio = res_OEratio$OE_Ratio[res_OEratio$Model == "Model4"],
               limit = 0.08, markers = FALSE, g = 5)
calplot_smooth(dat, "predrisk_mod5a", tmax = tmax, main = "Model 5a",
               C = res_Cindex$Cindex[res_Cindex$Model == "Model5a"],
               calslope = res_Slope$Slope[res_Slope$Model == "Model5a"],
               OEratio = res_OEratio$OE_Ratio[res_OEratio$Model == "Model5a"],
               limit = 0.08, markers = FALSE, g = 5)
calplot_smooth(dat, "predrisk_mod5b", tmax = tmax, main = "Model 5b",
               C = res_Cindex$Cindex[res_Cindex$Model == "Model5b"],
               calslope = res_Slope$Slope[res_Slope$Model == "Model5b"],
               OEratio = res_OEratio$OE_Ratio[res_OEratio$Model == "Model5b"],
               limit = 0.08, markers = FALSE, g = 5)

par(mfrow = c(1, 1))
```

## Decision analysis: Net benefit
```{r dca}
thresholdmax <- 0.10

# Define a function to compute NB for each model
computeNB_for_model <- function(predictions) {
  computeNB(outcome_FUP = dat$futime,
            outcome_num = dat$bc,
            predictions = predictions,
            weights = dat$wt,
            tp = tmax,
            thresholdmax = thresholdmax)
}

# Compute NB for all models
NB_results <- lapply(predrisk_cols, computeNB_for_model)

# Combine results
NB_df <- NB_results[[1]][, c("threshold", "NB_all")]
for (i in 1:length(NB_results)) {
    NB_df[[paste0("NB_mod", i)]] <- NB_results[[i]]$NB
}

NB_df <- NB_df %>% rename(
  NB_mod3a = NB_mod3,
  NB_mod3b = NB_mod4,
  NB_mod4 = NB_mod5,
  NB_mod5a = NB_mod6,
  NB_mod5b = NB_mod7)

# Event Rate
  eventrate = 1 - summary(survfit(Surv(futime, bc) ~ 1, weights = wt, data = dat),#
                        times = tmax)$surv
  eventrate

# Plot DCA
  colors <- viridis(8, option = "turbo")
  
  par(las = 1, xaxs = "i", yaxs = "i")
  plot(NB_df$threshold,
       NB_df$NB_all*1000,
       type = "l", lwd = 3, lty = 1, col = colors[1],
       xlab = "Threshold probability", ylab = "Net benefit (per 1000)",
       xlim = c(0, 0.06), ylim = c(-1, 8), bty = "n",
       cex.lab = 1, cex.axis = 1)
  abline(v=0.017, col="gray", lty=2, lwd=1)
  abline(v=0.03, col="gray", lty=2, lwd=1)
  abline(h=0, col="black", lwd=1)
  
  text(x = 0.024, y = 7.25, labels = "Risk-reducing\nmedication\nconsidered", col = "darkgray", cex = 0.8, font = 1)
  text(x = 0.037, y = 7.0, labels = "Risk-reducing\nmedication\nhighly\nrecommended", col = "darkgray", cex = 0.8, font = 1)

  smooth1 <- smooth.spline(NB_df$threshold, NB_df$NB_mod1*1000, spar=0.35)
  lines(smooth1, type = "l", lwd = 3, col=colors[2])
  smooth2 <- smooth.spline(NB_df$threshold, NB_df$NB_mod2*1000, spar=0.35)
  lines(smooth2, type = "l", lwd = 3, col=colors[3])
  smooth3a <- smooth.spline(NB_df$threshold, NB_df$NB_mod3a*1000, spar=0.35)
  lines(smooth3a, type = "l", lwd = 3, col=colors[4])
  smooth3b <- smooth.spline(NB_df$threshold, NB_df$NB_mod3b*1000, spar=0.35)
  lines(smooth3b, type = "l", lwd = 3, col=colors[5])
  smooth4 <- smooth.spline(NB_df$threshold, NB_df$NB_mod4*1000, spar=0.35)
  lines(smooth4, type = "l", lwd = 3, col=colors[6])
  smooth5a <- smooth.spline(NB_df$threshold, NB_df$NB_mod5a*1000, spar=0.35)
  lines(smooth5a, type = "l", lwd = 3, col=colors[7])
  smooth5b <- smooth.spline(NB_df$threshold, NB_df$NB_mod5b*1000, spar=0.35)
  lines(smooth5b, type = "l", lwd = 3, col=colors[8])
  
  legend("topright", legend = c("Treat all", model_names),
         lwd = 3, cex = 1, col = colors,
         bty = "n")

# Net Benefit at clinically relevant thresholds
NB_df_adjusted <- NB_df
NB_df_adjusted[,-1] <- round(NB_df_adjusted[,-1] * 1000, 0)

NB_selected <- NB_df_adjusted[NB_df_adjusted$threshold %in% c(0.017, 0.03), ]

# Results
rownames(NB_selected) <- NULL

kable(NB_selected, 
      format = "html", 
      col.names = c("Threshold", "NB_all", "NB_mod1", "NB_mod2", "NB_mod3a", "NB_mod3b", "NB_mod4", "NB_mod5a", "NB_mod5b")
      ) %>%
  kable_styling(
    full_width = FALSE, 
    bootstrap_options = c("striped", "hover")
  )
```

## Net reclassification
```{r nri}
# Define the function to compute NRI and confidence intervals
computeNRI_with_ci <- function(pred_old, pred_new) {
  
  nri_est <- round(computeNRI(
    outcome_FUP = dat$futime,
    outcome_num = dat$bc,
    predictions_old = pred_old,
    predictions_new = pred_new,
    tp = tmax,
    weights = dat$wt), 2)
  
  x1 <- 1:nrow(dat)
  b4 <- boot(x1, function(u, i)
    computeNRI(
      outcome_FUP = dat$futime[i],
      outcome_num = dat$bc[i],
      predictions_old = pred_old[i],
      predictions_new = pred_new[i],
      tp = tmax,
      weights = dat$wt[i]),
    R = 1000)
  
  # Compute bootstrap confidence intervals
  b4_ci_NRIev <- boot.ci(b4, type = c("norm", "basic", "perc"), index=1)
  NRIev_result <- paste0(nri_est["NRI Events"], " (", round(b4_ci_NRIev$percent[4], 2), ", ", round(b4_ci_NRIev$percent[5], 2), ")")

  b4_ci_NRInev <- boot.ci(b4, type = c("norm", "basic", "perc"), index=2)
  NRInev_result <- paste0(nri_est["NRI Non-Events"], " (", round(b4_ci_NRInev$percent[4], 2), ", ", round(b4_ci_NRInev$percent[5], 2), ")")

  b4_ci_NRIal <- boot.ci(b4, type = c("norm", "basic", "perc"), index=3)
  NRIal_result <- paste0(nri_est["Overall NRI"], " (", round(b4_ci_NRIal$percent[4], 2), ", ", round(b4_ci_NRIal$percent[5], 2), ")")
    
  # Format results with CIs
  result <- list(
    NRI_Events = NRIev_result,
    NRI_NonEvents = NRInev_result,
    Overall_NRI = NRIal_result)
  
  return(result)
}

# Initialize a dataframe to store results
res_NRI <- data.frame(
  Model_Comparison = character(),
  NRI_Events = character(),
  NRI_NonEvents = character(),
  Overall_NRI = character(),
  stringsAsFactors = FALSE
)

# Define the specific model comparisons (ensure correct indices)
model_comparisons <- list(
  c("Model 1", "Model 2"),
  c("Model 2", "Model 3a"),
  c("Model 2", "Model 3b"),
  c("Model 2", "Model 4"),
  c("Model 2", "Model 5a"),
  c("Model 2", "Model 5b")
)

model_indices <- list(
  c(1, 2),  # Model 1 vs Model 2
  c(2, 3),  # Model 2 vs Model 3a
  c(2, 4),  # Model 2 vs Model 3b
  c(2, 5),  # Model 2 vs Model 4
  c(2, 6),  # Model 2 vs Model 5a
  c(2, 7)   # Model 2 vs Model 5b
)

# Compute NRI for each comparison
for (i in seq_along(model_comparisons)) {
  model_pair <- model_comparisons[[i]]
  pred_old <- predrisk_cols[[model_indices[[i]][1]]]
  pred_new <- predrisk_cols[[model_indices[[i]][2]]]
  
  nri_result <- computeNRI_with_ci(pred_old, pred_new)
  
  res_NRI <- rbind(res_NRI, data.frame(
    Model_Comparison = paste(model_pair[1], "vs", model_pair[2]), 
    NRI_Events = nri_result$NRI_Events, 
    NRI_NonEvents = nri_result$NRI_NonEvents, 
    Overall_NRI = nri_result$Overall_NRI, 
    stringsAsFactors = FALSE
  ))
}

# Results
rownames(res_NRI) <- NULL

kable(res_NRI,
      format = "html", 
      col.names = c("Model Comparison", "NRI Events (95% CI)", "NRI Non-Events (95% CI)", "Overall NRI (95% CI)")
      ) %>%
  kable_styling(
    full_width = FALSE, 
    bootstrap_options = c("striped", "hover")
  )
```